name: Jaksim31-Frontend CI/CD

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
    types: [ "opened", "assigned", "synchronize", "labeled", "reopened" ]
    
jobs:
  Jaksim31-Front-CI:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          
      # NPM install & Build
      - name: Install and Build
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: |
          npm install
          npm install sharp
          npm run build      
      
      # NPM caching
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'      
      
      # E2E Test - Cypress
      - name: Run Cypress E2E test
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          spec: |
            cypress/e2e/member/userLogin.cy.js
            cypress/e2e/member/userInfo.cy.js
            cypress/e2e/diary/diarySave.cy.js
            cypress/e2e/diary/diaryList.cy.js
            cypress/e2e/diary/diaryEdit.cy.js
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
